<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_setting</name>
   <tag></tag>
   <elementGuidId>e8b8ea23-2f52-4ddf-bdc8-032d17b74d60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[7]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[7]/a/span</value>
   </webElementProperties>
</WebElementEntity>
