<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_setting_ubah_password</name>
   <tag></tag>
   <elementGuidId>93efad50-b339-4e11-bfe2-1b7d01eb8492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[7]/ul/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[7]/ul/li[5]/a</value>
   </webElementProperties>
</WebElementEntity>
