<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_dashboard</name>
   <tag></tag>
   <elementGuidId>cdfe1607-57d3-4b2e-947f-f0db9756adaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;sidebar-menu&quot;]/div/ul/li[1]/a</value>
   </webElementProperties>
</WebElementEntity>
